-- Generated by Envision Gui2Lua, VER-1, 0-18.

local Instances = {
	Loader = Instance.new("ScreenGui"),
	Loader_2 = Instance.new("Frame"),
	UICorner = Instance.new("UICorner"),
	Title = Instance.new("TextLabel"),
	version = Instance.new("TextLabel"),
	Backround = Instance.new("TextLabel"),
	UICorner_2 = Instance.new("UICorner"),
	UIStroke = Instance.new("UIStroke"),
	UIPadding = Instance.new("UIPadding"),
	XYNMiseryUIBackround = Instance.new("TextLabel"),
	UICorner_3 = Instance.new("UICorner"),
	UIStroke_2 = Instance.new("UIStroke"),
	UIPadding_2 = Instance.new("UIPadding"),
	WhatToLoad = Instance.new("TextLabel"),
	LoadMiseryUIButton = Instance.new("TextButton"),
	UICorner_4 = Instance.new("UICorner"),
	UIStroke_3 = Instance.new("UIStroke"),
	XYNCelexUIBackround = Instance.new("TextLabel"),
	UICorner_5 = Instance.new("UICorner"),
	UIStroke_4 = Instance.new("UIStroke"),
	UIPadding_3 = Instance.new("UIPadding"),
	WhatToLoad_2 = Instance.new("TextLabel"),
	LoadCelexUIButton = Instance.new("TextButton"),
	UICorner_6 = Instance.new("UICorner"),
	UIStroke_5 = Instance.new("UIStroke"),
	UIStroke_6 = Instance.new("UIStroke"),
	TimeLeft = Instance.new("TextLabel"),
}

Instances.Loader.Name = "Loader"
Instances.Loader.Parent = game.StarterGui

Instances.Loader_2.Name = "Loader"
Instances.Loader_2.Parent = Instances.Loader
Instances.Loader_2.Size = UDim2.new(0, 396, 0, 249)
Instances.Loader_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Loader_2.Position = UDim2.new(0.392988026, 0, 0.368333578, 0)
Instances.Loader_2.BorderSizePixel = 0
Instances.Loader_2.BackgroundColor3 = Color3.fromRGB(15, 15, 15)

Instances.UICorner.Name = "UICorner"
Instances.UICorner.Parent = Instances.Loader_2
Instances.UICorner.CornerRadius = UDim.new(0, 12)

Instances.Title.Name = "Title"
Instances.Title.Parent = Instances.Loader_2
Instances.Title.Size = UDim2.new(0, 147, 0, 50)
Instances.Title.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Title.BackgroundTransparency = 1
Instances.Title.Position = UDim2.new(0.244948998, 0, 0.112450004, 0)
Instances.Title.BorderSizePixel = 0
Instances.Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.Title.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.Title.Text = "xyn.lol"
Instances.Title.TextSize = 30
Instances.Title.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.version.Name = "version"
Instances.version.Parent = Instances.Loader_2
Instances.version.Size = UDim2.new(0, 106, 0, 57)
Instances.version.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.version.BackgroundTransparency = 1
Instances.version.Position = UDim2.new(0.48989898, 0, 0.112450041, 0)
Instances.version.BorderSizePixel = 0
Instances.version.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.version.TextColor3 = Color3.fromRGB(227, 181, 200)
Instances.version.Text = "v0.0.1"
Instances.version.TextSize = 20
Instances.version.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.Backround.Name = "Backround"
Instances.Backround.Parent = Instances.Loader_2
Instances.Backround.Size = UDim2.new(0, 274, 0, 130)
Instances.Backround.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.Backround.Position = UDim2.new(0.154040247, 0, 0.341365695, 0)
Instances.Backround.BorderSizePixel = 0
Instances.Backround.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
Instances.Backround.TextColor3 = Color3.fromRGB(50, 50, 50)
Instances.Backround.Text = ""
Instances.Backround.TextXAlignment = Enum.TextXAlignment.Left
Instances.Backround.TextSize = 14
Instances.Backround.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UICorner_2.Name = "UICorner"
Instances.UICorner_2.Parent = Instances.Backround

Instances.UIStroke.Name = "UIStroke"
Instances.UIStroke.Parent = Instances.Backround
Instances.UIStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke.Thickness = 1.399999976158142

Instances.UIPadding.Name = "UIPadding"
Instances.UIPadding.Parent = Instances.Backround
Instances.UIPadding.PaddingLeft = UDim.new(0, 10)

Instances.XYNMiseryUIBackround.Name = "XYNMiseryUIBackround"
Instances.XYNMiseryUIBackround.Parent = Instances.Backround
Instances.XYNMiseryUIBackround.Size = UDim2.new(0, 253, 0, 51)
Instances.XYNMiseryUIBackround.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.XYNMiseryUIBackround.Position = UDim2.new(-2.31193781e-07, 0, 0.0791099817, 0)
Instances.XYNMiseryUIBackround.BorderSizePixel = 0
Instances.XYNMiseryUIBackround.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
Instances.XYNMiseryUIBackround.TextColor3 = Color3.fromRGB(50, 50, 50)
Instances.XYNMiseryUIBackround.Text = ""
Instances.XYNMiseryUIBackround.TextXAlignment = Enum.TextXAlignment.Left
Instances.XYNMiseryUIBackround.TextSize = 14
Instances.XYNMiseryUIBackround.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UICorner_3.Name = "UICorner"
Instances.UICorner_3.Parent = Instances.XYNMiseryUIBackround

Instances.UIStroke_2.Name = "UIStroke"
Instances.UIStroke_2.Parent = Instances.XYNMiseryUIBackround
Instances.UIStroke_2.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke_2.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke_2.Thickness = 1.399999976158142

Instances.UIPadding_2.Name = "UIPadding"
Instances.UIPadding_2.Parent = Instances.XYNMiseryUIBackround
Instances.UIPadding_2.PaddingLeft = UDim.new(0, 10)

Instances.WhatToLoad.Name = "WhatToLoad"
Instances.WhatToLoad.Parent = Instances.XYNMiseryUIBackround
Instances.WhatToLoad.Size = UDim2.new(0, 109, 0, 19)
Instances.WhatToLoad.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.WhatToLoad.BackgroundTransparency = 1
Instances.WhatToLoad.Position = UDim2.new(-0.0056584361, 0, 0.297789335, 0)
Instances.WhatToLoad.BorderSizePixel = 0
Instances.WhatToLoad.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.WhatToLoad.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.WhatToLoad.Text = "xyn : misery ui"
Instances.WhatToLoad.TextSize = 15
Instances.WhatToLoad.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.LoadMiseryUIButton.Name = "LoadMiseryUIButton"
Instances.LoadMiseryUIButton.Parent = Instances.XYNMiseryUIBackround
Instances.LoadMiseryUIButton.Size = UDim2.new(0, 62, 0, 27)
Instances.LoadMiseryUIButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LoadMiseryUIButton.Position = UDim2.new(0.716048896, 0, 0.216867492, 0)
Instances.LoadMiseryUIButton.BorderSizePixel = 0
Instances.LoadMiseryUIButton.BackgroundColor3 = Color3.fromRGB(157, 125, 138)
Instances.LoadMiseryUIButton.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.LoadMiseryUIButton.Text = "Load"
Instances.LoadMiseryUIButton.TextSize = 14
Instances.LoadMiseryUIButton.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UICorner_4.Name = "UICorner"
Instances.UICorner_4.Parent = Instances.LoadMiseryUIButton

Instances.UIStroke_3.Name = "UIStroke"
Instances.UIStroke_3.Parent = Instances.LoadMiseryUIButton
Instances.UIStroke_3.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke_3.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke_3.Thickness = 1.399999976158142

Instances.XYNCelexUIBackround.Name = "XYNCelexUIBackround"
Instances.XYNCelexUIBackround.Parent = Instances.Backround
Instances.XYNCelexUIBackround.Size = UDim2.new(0, 253, 0, 51)
Instances.XYNCelexUIBackround.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.XYNCelexUIBackround.Position = UDim2.new(-2.31193781e-07, 0, 0.525263608, 0)
Instances.XYNCelexUIBackround.BorderSizePixel = 0
Instances.XYNCelexUIBackround.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
Instances.XYNCelexUIBackround.TextColor3 = Color3.fromRGB(50, 50, 50)
Instances.XYNCelexUIBackround.Text = ""
Instances.XYNCelexUIBackround.TextXAlignment = Enum.TextXAlignment.Left
Instances.XYNCelexUIBackround.TextSize = 14
Instances.XYNCelexUIBackround.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UICorner_5.Name = "UICorner"
Instances.UICorner_5.Parent = Instances.XYNCelexUIBackround

Instances.UIStroke_4.Name = "UIStroke"
Instances.UIStroke_4.Parent = Instances.XYNCelexUIBackround
Instances.UIStroke_4.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke_4.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke_4.Thickness = 1.399999976158142

Instances.UIPadding_3.Name = "UIPadding"
Instances.UIPadding_3.Parent = Instances.XYNCelexUIBackround
Instances.UIPadding_3.PaddingLeft = UDim.new(0, 10)

Instances.WhatToLoad_2.Name = "WhatToLoad"
Instances.WhatToLoad_2.Parent = Instances.XYNCelexUIBackround
Instances.WhatToLoad_2.Size = UDim2.new(0, 117, 0, 19)
Instances.WhatToLoad_2.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.WhatToLoad_2.BackgroundTransparency = 1
Instances.WhatToLoad_2.Position = UDim2.new(-0.0411522649, 0, 0.278181493, 0)
Instances.WhatToLoad_2.BorderSizePixel = 0
Instances.WhatToLoad_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.WhatToLoad_2.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.WhatToLoad_2.Text = "xyn : celex ui"
Instances.WhatToLoad_2.TextSize = 15
Instances.WhatToLoad_2.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.LoadCelexUIButton.Name = "LoadCelexUIButton"
Instances.LoadCelexUIButton.Parent = Instances.XYNCelexUIBackround
Instances.LoadCelexUIButton.Size = UDim2.new(0, 62, 0, 27)
Instances.LoadCelexUIButton.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.LoadCelexUIButton.Position = UDim2.new(0.716048896, 0, 0.216867492, 0)
Instances.LoadCelexUIButton.BorderSizePixel = 0
Instances.LoadCelexUIButton.BackgroundColor3 = Color3.fromRGB(157, 125, 138)
Instances.LoadCelexUIButton.TextColor3 = Color3.fromRGB(255, 255, 255)
Instances.LoadCelexUIButton.Text = "Load"
Instances.LoadCelexUIButton.TextSize = 14
Instances.LoadCelexUIButton.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

Instances.UICorner_6.Name = "UICorner"
Instances.UICorner_6.Parent = Instances.LoadCelexUIButton

Instances.UIStroke_5.Name = "UIStroke"
Instances.UIStroke_5.Parent = Instances.LoadCelexUIButton
Instances.UIStroke_5.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke_5.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke_5.Thickness = 1.399999976158142

Instances.UIStroke_6.Name = "UIStroke"
Instances.UIStroke_6.Parent = Instances.Loader_2
Instances.UIStroke_6.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
Instances.UIStroke_6.Color = Color3.fromRGB(25, 25, 25)
Instances.UIStroke_6.Thickness = 1.399999976158142

Instances.TimeLeft.Name = "TimeLeft"
Instances.TimeLeft.Parent = Instances.Loader_2
Instances.TimeLeft.Size = UDim2.new(0, 100, 0, 19)
Instances.TimeLeft.BorderColor3 = Color3.fromRGB(0, 0, 0)
Instances.TimeLeft.BackgroundTransparency = 1
Instances.TimeLeft.Position = UDim2.new(0.363402545, 0, 0.898072898, 0)
Instances.TimeLeft.BorderSizePixel = 0
Instances.TimeLeft.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Instances.TimeLeft.TextColor3 = Color3.fromRGB(122, 122, 122)
Instances.TimeLeft.Text = "Expires in: 30 days"
Instances.TimeLeft.TextSize = 12
Instances.TimeLeft.FontFace = Font.new("rbxassetid://11702779517", Enum.FontWeight.Bold, Enum.FontStyle.Normal)

-- Function "DragScript"


	
	
	local UIS = game:GetService('UserInputService')
	local frame = Instances.Loader_2
	local dragToggle = nil
	local dragSpeed = 0.25
	local dragStart = nil
	local startPos = nil
	local function updateInput(input)
		local delta = input.Position - dragStart
		local position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X,
			startPos.Y.Scale, startPos.Y.Offset + delta.Y)
		game:GetService('TweenService'):Create(frame, TweenInfo.new(dragSpeed), {Position = position}):Play()
	end
	frame.InputBegan:Connect(function(input)
		if (input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch) then 
			dragToggle = true
			dragStart = input.Position
			startPos = frame.Position
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragToggle = false
				end
			end)
		end
	end)
	UIS.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			if dragToggle then
				updateInput(input)
			end
		end
	end)
	


Instances.LoadMiseryUIButton.MouseButton1Click:Connect(function()
	-- HERE YOU LOAD THE MISERY UI
	
	wait(1)
	Instances.Loader:Destroy()
end)

Instances.LoadCelexUIButton.MouseButton1Click:Connect(function()
	-- HERE YOU LOAD THE CELEX UI
	
	wait(1)
	Instances.Loader:Destroy()
end)
